name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          latexmk_shell_escape: true
          latexmk_use_lualatex: true
      - name: Upload LaTeX Resume
        uses: actions/upload-artifact@v2
        with:
          name: Resume
          path: resume.pdf
